### PR TITLE
Notifications implementation

### PR DESCRIPTION
**Pull request by Antoine444**
This PR introduces a core feature of the app, that is the notifications. Now an user can see all notifications related to the invitations of an event he has received which he needs to either accept or decline. This screen can be found in the `Profile` screen and click on the little bell button.

In this PR, we implemented the accept and refuse invitations logic in the `EventViewModel` and `UserViewModel` that will be used in the `Notifications` screen. All pending invitations are displayed in that screen as a `Card` component in which there are the `Accept` and `Decline` buttons. When clicking on either on these buttons they become disabled and when the user goes back to the previous screen, the updates on the `event` and the `current user` are made, meaning the `pendingRequest` field of the `GoMeetUser` doesn't store the current user anymore and the field `joinedEvents` stores the current user now. Same logic for the `Event`: the `pendingParticipants` field doesn't store the current user anymore and the `participants` field stores the current user now.

We also added all documentations related to the invitations logic in this PR.

### CODE REVIEW

**Review by koma2323 — CHANGES_REQUESTED** [review]
- Accepting/declining invites doesn't seem to do anything: if i go to another screen and go back to my notifications, the invite is still there and i can still accept/decline it and i see no change in the events tab
- i recommend changing the ui a bit: make the notification cards more similar to the ones in Events/Trends and the text above the cards that says "x invited you to attend" is barely visible in dark mode

**Comment by koma2323** [comment]
ui comparison:
IMG_20240516_112950
IMG_20240516_113006

**Comment by Antoine444** [comment]
> * Accepting/declining invites doesn't seem to do anything: if i go to another screen and go back to my notifications, the invite is still there and i can still accept/decline it
> * i recommend changing the ui a bit: make the notification cards more similar to the ones in Events/Trends and the text above the cards that says "x invited you to attend" is barely visible in dark mode

For the first point, it works properly on my side, the fields are updated on Firebase and the notifications don't show up anymore after the update. Are you sure it doesn't work on your side ? I did find an issue tho, that is the UI of ManageInvites doesn't update when the user has accepted or refused an invitation, I made an issue about it and will be fix soon.
For the UI, I could modify the "x invited you to attend" so that it is more visible in dark mode I agree but the UIs for the `Card` are very similar in `Event` and in `Notifications`, that is something we could change or discuss later with the other developers of the app.

Thank you for your review !

**Comment by koma2323** [comment]
> > * Accepting/declining invites doesn't seem to do anything: if i go to another screen and go back to my notifications, the invite is still there and i can still accept/decline it
> > * i recommend changing the ui a bit: make the notification cards more similar to the ones in Events/Trends and the text above the cards that says "x invited you to attend" is barely visible in dark mode
> 
> For the first point, it works properly on my side, the fields are updated on Firebase and the notifications don't show up anymore after the update. Are you sure it doesn't work on your side ? I did find an issue tho, that is the UI of ManageInvites doesn't update when the user has accepted or refused an invitation, I made an issue about it and will be fix soon. For the UI, I could modify the "x invited you to attend" so that it is more visible in dark mode I agree but the UIs for the `Card` are very similar in `Event` and in `Notifications`, that is something we could change or discuss later with the other developers of the app.
> 
> Thank you for your review !

I trust you if you say it works on your side. As for the ui, I still think we should change the outline of the cards to blue or black/white instead of cyan since that's what we've been doing in the rest of the app

**Comment by Antoine444** [comment]
> > > * Accepting/declining invites doesn't seem to do anything: if i go to another screen and go back to my notifications, the invite is still there and i can still accept/decline it
> > > * i recommend changing the ui a bit: make the notification cards more similar to the ones in Events/Trends and the text above the cards that says "x invited you to attend" is barely visible in dark mode
> > 
> > 
> > For the first point, it works properly on my side, the fields are updated on Firebase and the notifications don't show up anymore after the update. Are you sure it doesn't work on your side ? I did find an issue tho, that is the UI of ManageInvites doesn't update when the user has accepted or refused an invitation, I made an issue about it and will be fix soon. For the UI, I could modify the "x invited you to attend" so that it is more visible in dark mode I agree but the UIs for the `Card` are very similar in `Event` and in `Notifications`, that is something we could change or discuss later with the other developers of the app.
> > Thank you for your review !
> 
> I trust you if you say it works on your side. As for the ui, I still think we should change the outline of the cards to blue or black/white instead of cyan since that's what we've been doing in the rest of the app

Just to be sure, we can ask a second reviewer to check if it works on their side too or not :) For the UI, I can work on it this evening, if this works for you.

**Review by koma2323 — APPROVED** [review]
nice work, the notifications now seem to work perfectly and the ui was fixed to match the rest of the app

**Pull request merged**
